babel/eslint-plugin-babel

README.md
index.js
rules/new-cap.js
tests/new-cap.js

Added support for decorators in the new-cap rule.

---

README.md
index.js
rules/object-curly-spacing.js
tests/object-curly-spacing.js

Just like https://github.com/babel/eslint-plugin-babel/pull/3 but for it's object-only version, since `space-in-brackets` is deprecated.

Added support for experimental exports in the `object-curly-spacing` rule

---

package.json

it works fine for me, but:
```
npm ERR! peerinvalid The package eslint@1.0.0-rc-1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer eslint-plugin-babel@1.2.0 wants eslint@>=0.8.0
```

support eslint@>=1.0.0-rc-1

---

README.md
package.json
rules/arrow-parens.js
tests/arrow-parens.js

Fixes #8
Depends on a fix in babel-eslint I will make, which is to keep `node.async`
Ref https://github.com/babel/babel-eslint/pull/166
https://github.com/babel/babel-eslint/blob/f5d9f37a36978adaa660d0515cd58bff56380181/acorn-to-esprima.js#L242-L245
@leebyron

Add support for async functions in arrow-parens

---

index.js

eslint-plugin-babel@2.1.0 added the arrow-parens rule, however trying to use it causes a not found error:
```
1:1  warning  Definition for rule 'babel/arrow-parens' was not found  babel/arrow-parens
```
arrow-parens needs to be added to index.js

add arrow-parens to index.js

---

index.js
rules/no-await-in-loop.js
tests/no-await-in-loop.js

Add no-await-in-loop rule.

---

README.md

Fix typo in README rules section

---

rules/object-curly-spacing.js
tests/object-curly-spacing.js

cherry picked form eslint/eslint/commit/1dcca0c95b894a91dc466ab5692292a99f717d54

Update: Implement auto fix for object-curly-spacing (fixes #37)

---

rules/arrow-parens.js
tests/arrow-parens.js

When using optional type annotations, parentheses are required even for
single-argument arrow functions. Check for a `typeAnnotation` on the
single param and allow parentheses if it exists.
// good with "as-needed"
a => 5;
(a: string) => 5; // Previously this reported an error
// bad with "as-needed"
(a) => 5;

Add type annotations to arrow-parens "as-needed"

---

index.js
rules/flow-object-type.js
tests/flow-object-type.js

In addition to the automated tests, I tested manually with:
- the rule not mentioned in .eslintrc -> the rule gave no results
- no options provided -> preferred semicolons
- 'semicolon' option provided -> preferred semicolons
- 'comma' option provided -> preferred commas
CC @zpao

Add flow-object-type rule

---

rules/arrow-parens.js
tests/arrow-parens.js

This PR adds an automated fix for `babel/arrow-parens`. If parens are needed, it adds them, if not, it removes them. Let me know if you'd like me to raise an issue for this in addition to the PR, or if you don't think this should be added.
cc/ @hzoo

Add an automated fix for arrow-parens

---

README.md
index.js
rules/func-params-comma-dangle.js
tests/func-params-comma-dangle.js

Like [`comma-dangle`](http://eslint.org/docs/rules/comma-dangle), with the same options, but for [trailing commas in function parameter lists](https://github.com/jeffmo/es-trailing-function-commas).
There is a bug in the AST, where in arrows functions, the loc's for params with flow types only cover the argument identifier (or rest element), and not the flow type. So for this case, this rule is a noop. I'll have to investigate it separately.

Add func-params-comma-dangle rule

---

.travis.yml

There wasn't an issue for this, but I figured the CI tests should be running in the same versions that `babel-eslint`'s tests are being run. Here's the [babel-eslint .travis.yml file](https://github.com/babel/babel-eslint/blob/master/.travis.yml).

Run Travis CI in same Node versions as babel-eslint

---

README.md
ast-utils.js
index.js
package.json
rules/no-invalid-this.js
tests/rules/no-invalid-this.js

This is to help closes #12. The implementation is really rudimentary, whenever inside a class property it considers all `this` to be valid. I tried to think about it a bit, is there any scenario where it isn't the case?
All files are taken from ESLint since this proposal is still only stage 2, but might make its way into ESLint if it ever reaches stage 4 (hopefully!):
- https://github.com/eslint/eslint/blob/ce590e28ee4146ab04974c8f768b169538059585/lib/ast-utils.js
- https://github.com/eslint/eslint/blob/ce590e28ee4146ab04974c8f768b169538059585/lib/rules/no-invalid-this.js
- https://github.com/eslint/eslint/blob/ce590e28ee4146ab04974c8f768b169538059585/tests/lib/rules/no-invalid-this.js
Build fails on 0.10 and 0.12 because of https://github.com/babel/eslint-plugin-babel/pull/71#issuecomment …

Added `babel/no-invalid-this`

---

.travis.yml
package.json

Since `eslint-plugin-babel` has `babel-eslint` which has been dropped support of Node < 4 already, this should drop as follow as [`babel-eslint`](https://github.com/babel/babel-eslint/blob/master/package.json#L33).

Drop support of Node < 4

---

.travis.yml

As discussed in https://github.com/babel/eslint-plugin-babel/pull/71#issuecomment-230582590 and https://github.com/babel/eslint-plugin-babel/pull/101#issuecomment-257962422
Could be nice to cut a release too. :grin: 
Thanks!
cc @jquense @hzoo

Updated Node versions to test against in the Travis configuration

---

rules/array-bracket-spacing.js
rules/arrow-parens.js
rules/flow-object-type.js
rules/func-params-comma-dangle.js
rules/generator-star-spacing.js
rules/object-shorthand.js

In order to programmatically document the `deprecated` rules, I had to upgrade each of them to the [new ESLint rule format](http://eslint.org/docs/developer-guide/working-with-rules). 
Alongside the `schema` array, you will see the addition of the `deprecated` flag in each rules `meta` object.
This PR should [resolve this issue](https://github.com/babel/eslint-plugin-babel/issues/118#issuecomment-273203318).

Updated deprecated rules to new format and added deprecated flag to their meta object

---

README.md
index.js
rules/semi.js
tests/rules/semi.js

Add babel semi

---

README.md
rules/semi.js
tests/rules/semi.js

The [async iterator proposal](https://github.com/tc39/proposal-async-iteration) adds support for the following code
```
for await (const line of readLines(filePath)) {
console.log(line);
}
async function* readLines(path) {
let file = await fileOpen(path);
try {
while (!file.EOF) {
yield await file.readLine();
}
} finally {
await file.close();
}
}
```
However, the ESLint rule expects there to be a semi-colon. Since this is currently a stage-3 proposal, the ESLint team has declined implementing it at this time per https://github.com/eslint/eslint/pull/7417

Modifying semi rule to support for await

---

README.md
package.json
rules/quotes.js
tests/rules/quotes.js
yarn.lock

Depends on https://github.com/babel/eslint-plugin-babel/pull/138.
Until acorn is bumped in ESLint (ref: https://github.com/eslint/eslint/issues/9662), this allows the JSX fragment shorthand syntax to not trip the `quotes` rule.
Related babel-eslint thread:
https://github.com/babel/babel-eslint/issues/554

Add babel/quotes rule for JSXFragment workaround

---

README.md
index.js
rules/no-unused-expressions.js
tests/rules/no-unused-expressions.js

/cc #13 
I haven't really done any work with babel's AST before, so I'm sure I'm missing a ton of cases.

add no-unused-expressions with do expressions support

---

rules/no-unused-expressions.js
tests/rules/no-unused-expressions.js

This relates to the issue outlined here: https://github.com/babel/babel-eslint/issues/643

Support optional calls in no-unused-expressions

---

README.md
rules/valid-typeof.js
tests/rules/valid-typeof.js

Closes https://github.com/babel/eslint-plugin-babel/issues/153

Add valid-typeof rule with support for BigInt

---

rules/no-invalid-this.js
tests/rules/no-invalid-this.js

Closes #182 
Also count `node.type === ClassPrivateProperty` as being a class property.

Support private properties in no-invalid-this
